Update servo parameters - studio_ws
PickNikRobotics/moveit_studio_ur_ws pull request #173
Opened 2024-01-15 19:04 UTC by pac48

This PR allows Studio to use the new acceleration-based smoothing plugin for servo. The hard joint limits need to be tested and verified.

Requires:
- [x] https://github.com/ros-planning/moveit2/pull/2651

2024-01-16 09:25 UTC, sjahr requested changes
Not sure if we need a streaming controller at all (more in the comments) but maybe I am missing something. CI probably fails due to https://github.com/ros-planning/moveit2/pull/2651 not yet being merged

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_base_config/config/control/picknik_ur.ros2_control.yaml
> +      type: joint_trajectory_controller/JointTrajectoryController
I think calling a JTC-type controller a streaming controller is confusing. If we need this for servo, you should rename the controller completely. Can't you use `joint_trajectory_controller` or does it one have a specific config?

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_base_config/config/control/picknik_ur.ros2_control.yaml
> +      - velocity
Looks like this config is a similar to `joint_trajectory_controller`. Can't you use it instead? Is the streaming controller only used by servo? In that case we could remove it completely :thinking:

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_base_config/config/moveit/hard_joint_limits.yaml
> +    # we artificially limit this joint to half its actual joint position limit
Really nice comments with additional explanation!

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_base_config/config/moveit/ur_servo.yaml
> +smoothing_filter_plugin_name: "online_signal_smoothing::AccelerationLimitedPlugin"
Can you add a small comment in the PR description that this PR depends on the moveit2 PR that adds this and requires an dependency update of moveit2 in studio

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_gazebo_config/config/control/picknik_ur5e.ros2_control.yaml
> +      type: joint_trajectory_controller/JointTrajectoryController
Same comments as above

2024-01-16 09:25 UTC, sjahr commented on src/picknik_ur_gazebo_config/config/moveit/ur_servo.yaml
> +command_out_topic: /streaming_controller/joint_trajectory # Publish outgoing commands here
Might need an update

2024-01-16 16:27 UTC, pac48 commented
> Not sure if we need a streaming controller at all (more in the comments) but maybe I am missing something. CI probably fails due to [ros-planning/moveit2#2651](https://github.com/ros-planning/moveit2/pull/2651) not yet being merged

The problem is that the streaming controller is referred to in the behaviors, like [here](https://github.com/PickNikRobotics/moveit_studio_ws/blob/18930844cf1dbe292a8bda17ed22d1e05d2c6a5f/src/picknik_ur_base_config/objectives/teleoperate_joint_jog.xml#L5). If we want the servo controller to be configurable, then it needs to be done this way.

2024-01-17 07:22 UTC, sjahr commented
> > Not sure if we need a streaming controller at all (more in the comments) but maybe I am missing something. CI probably fails due to [ros-planning/moveit2#2651](https://github.com/ros-planning/moveit2/pull/2651) not yet being merged
> 
> The problem is that the streaming controller is referred to in the behaviors, like [here](https://github.com/PickNikRobotics/moveit_studio_ws/blob/18930844cf1dbe292a8bda17ed22d1e05d2c6a5f/src/picknik_ur_base_config/objectives/teleoperate_joint_jog.xml#L5). If we want the servo controller to be configurable, then it needs to be done this way.

Let's call it `servo_controller` in that case and add a comment that describes why it is necessary to have it in addition to the default JTC

2024-01-19 22:04 UTC, pac48 commented on src/picknik_ur_gazebo_config/config/moveit/ur_servo.yaml
> +command_out_topic: /streaming_controller/joint_trajectory # Publish outgoing commands here
Fixed, thanks!

2024-01-19 22:05 UTC, pac48 commented
> > > Not sure if we need a streaming controller at all (more in the comments) but maybe I am missing something. CI probably fails due to [ros-planning/moveit2#2651](https://github.com/ros-planning/moveit2/pull/2651) not yet being merged
> > 
> > 
> > The problem is that the streaming controller is referred to in the behaviors, like [here](https://github.com/PickNikRobotics/moveit_studio_ws/blob/18930844cf1dbe292a8bda17ed22d1e05d2c6a5f/src/picknik_ur_base_config/objectives/teleoperate_joint_jog.xml#L5). If we want the servo controller to be configurable, then it needs to be done this way.
> 
> What do you think about calling it `servo_controller` in that case and add a comment that describes why it is necessary to have it in addition to the default JTC

@sjahr I renamed the controller to `servo_controller`. I think it is a better and more descriptive name.

2024-01-22 09:41 UTC, sjahr approved these changes
Thanks!

2024-01-23 14:55 UTC, merged