Update camera launch logic
PickNikRobotics/moveit_studio_ur_ws pull request #252
Opened 2024-04-04 13:23 UTC by sjahr

Address changes introduced by https://github.com/PickNikRobotics/moveit_studio/pull/6966

Requires also https://github.com/PickNikRobotics/picknik_ur5e_configs/pull/69

See https://github.com/PickNikRobotics/picknik_ut_moveit_studio_ws/pull/27 as a working reference

# TODO
- [ ] Test on HW
  - Decide when and where the cameras should be automatically launched

2024-04-04 14:07 UTC, EzraBrooks requested changes
The serial number bug is specifically because of YAML coercing numbers that start with `0` into octal - so if we entirely eliminate the `cameras.yaml`, which is no longer needed, and just do this in XML launch files, it'll be very simple.

2024-04-12 18:40 UTC, pac48 commented on src/picknik_ur_base_config/launch/rs_cameras.launch.xml
> +    <arg name="serial_no" value="$(arg scene_camera_serial_no)"/>
```suggestion
    <arg name="serial_no" value="$(var scene_camera_serial_no)"/>
```

2024-04-12 18:41 UTC, pac48 commented on src/picknik_ur_base_config/launch/rs_cameras.launch.xml
> +    <arg name="serial_no" value="$(arg wrist_mounted_camera_serial_no)"/>
```suggestion
    <arg name="serial_no" value="$(var wrist_mounted_camera_serial_no)"/>
```

2024-04-12 18:45 UTC, pac48 commented
I tried to test these PRs (https://github.com/PickNikRobotics/picknik_ur5e_configs/pull/69, https://github.com/PickNikRobotics/moveit_studio_ur_ws/pull/252) on the hardware and ran into a few issues. I added a suggested change for the camera launch file args. I think you need to use the `var` keyword instead of `arg`. 

Also, I had to install the  realsense2-camera package manually, so I think the package.xml needs to be updated. 

It worked after changing those things.

2024-04-17 17:42 UTC, pac48 submitted a review, later dismissed

2024-04-19 15:23 UTC, pac48 approved these changes

2024-04-19 15:24 UTC, merged