Add useful description to cycle_between_waypoints.xml
PickNikRobotics/moveit_studio_ur_ws pull request #307
Opened 2024-07-10 19:33 UTC by davetcoleman

The current description is a repeat of the Objective name, and so is useless.

2024-07-10 19:33 UTC, davetcoleman commented
I think this should also be copied to our Mujoco config

2024-07-10 21:41 UTC, jeremydbronson requested changes
`Example of repeatidly moving ` should be `Example of repeatedly moving`

2024-07-10 21:53 UTC, MikeWrock submitted a review, later dismissed

2024-07-10 23:06 UTC, davetcoleman commented
> `Example of repeatidly moving ` should be `Example of repeatedly moving`

Thanks, there's no spell check in the Github code editor. I'll be more careful next time. Fixed!

2024-07-11 19:23 UTC, jeremydbronson approved these changes

2024-07-12 17:22 UTC, merged