Add comments and explanation to joint_diagnostic
PickNikRobotics/moveit_studio_ur_ws pull request #308
Opened 2024-07-10 19:39 UTC by davetcoleman

Added explanation of what the objective is suppose to do, since its not obvious you have to have almost identical waypoint names. Inline documentation!

2024-07-10 19:39 UTC, davetcoleman commented
I think this should also be copied to our Mujoco config

2024-07-10 19:45 UTC, bgill92 requested changes
Looks good, other than spelling typos.

2024-07-10 19:45 UTC, bgill92 commented on src/picknik_ur_mock_hw_config/objectives/joint_diagnostic.xml
> +  <BehaviorTree ID="Joint Diagnostic" _description="Example of cycliing through the min and max limits of a single joint, for hardware testing" _favorite="true">
```suggestion
  <BehaviorTree ID="Joint Diagnostic" _description="Example of cycling through the min and max limits of a single joint, for hardware testing" _favorite="true">
```

2024-07-10 19:45 UTC, bgill92 commented on src/picknik_ur_mock_hw_config/objectives/joint_diagnostic.xml
> +          <!-- If you use two waypoints that have idential joint values, except for one joint, you can use this Objective as a way to test a single joint repeatidly. This is useful for things like ha
```suggestion
          <!-- If you use two waypoints that have identical joint values, except for one joint, you can use this Objective as a way to test a single joint repeatedly. This is useful for things like hardware diagnostics and hardware bringup.-->
```

2024-07-10 19:46 UTC, bgill92 commented
@davetcoleman I can add this `Joint Diagnostic` Objective to the MuJoCo config as well.

2024-07-10 19:50 UTC, davetcoleman commented
I just turned on a spell check extension to VSCode :-) 

Thanks for the review! I assume this is already in Mujoco config, just out of date?

2024-07-10 19:58 UTC, bgill92 commented
Yup, the `Joint Diagnostic` Objective is in the MuJoCo config, just not updated.

2024-07-10 20:35 UTC, davetcoleman commented
Seems like the CI is broken unrelated to this PR?

```
 picknik_ur_studio_integration_testing.TestGTestProcessPostShutdown test_gtest_pass
  <<< failure message
    Traceback (most recent call last):
      File "/__w/moveit_studio_ur_ws/moveit_studio_ur_ws/src/picknik_ur_studio_integration_testing/test/launch/test_get_planning_groups.test.py", line 62, in test_gtest_pass
        launch_testing.asserts.assertExitCodes(
      File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/asserts/assert_exit_codes.py", line 62, in assertExitCodes
        assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(
    AssertionError: Proc test_get_planning_groups-21 exited with code 1
  >>>

Summary: 136 tests, 0 errors, 8 failures, 14 skipped
```

2024-07-10 21:54 UTC, MikeWrock approved these changes

2024-07-11 19:41 UTC, davetcoleman commented
@bgill92 is this CI issue known? Should we just merge and ignore it?

2024-07-12 16:39 UTC, merged